Extracted drawing logic into separate component
infinitered/ai-lab pull request #39
Opened 2021-12-28 21:44 UTC by kateinkim

#### 1. Changes
- The types and interfaces are moved to `types.ts` file from `AILabImage.tsx`
- The logic for drawing boundary boxes is also moved into its own component

#### 2. Photo/Video
![CleanShot 2021-12-28 at 14 36 08](https://user-images.githubusercontent.com/53795920/147609208-bf62d52d-5895-497a-b611-990e76b07314.gif)

2021-12-28 23:34 UTC, GantMan requested changes
Allow `customDetectionUI` to be a prop of configuration.

Also, let's rename into AILab style

2021-12-28 23:34 UTC, GantMan commented on packages/ai-lab/src/components/AILabImage/AILabImage.tsx
> +import { DrawDetections } from '../DrawDetections';
Let's rename to AILabObjectDetctionUI

2021-12-29 21:58 UTC, kateinkim commented on packages/ai-lab/src/components/AILabImage/AILabImage.tsx
> +import { DrawDetections } from '../DrawDetections';
Fixed!

2021-12-29 22:02 UTC, kateinkim commented
I hope this is how it's supposed to be 😃

![CleanShot 2021-12-29 at 14 55 41](https://user-images.githubusercontent.com/53795920/147706667-326b4590-ff40-4a1b-bda4-d942784df323.gif)

2021-12-29 22:24 UTC, merged

2021-12-29 22:24 UTC, GantMan commented
![giphy](https://user-images.githubusercontent.com/997157/147707832-63e32379-1f97-4686-979a-c2d8ed6ce01b.gif)